import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from memtext.core import add_log, get_context_dir, init_context
from memtext.db import init_db, query_entries
from memtext.reflection import (
    estimate_tokens,
    format_logs_for_reflection,
    get_recent_session_logs,
    run_reflection_cycle,
    save_reflection_insight,
)


@pytest.fixture
def clean_env(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    init_context()
    init_db()
    return get_context_dir()


class TestReflectionEngine:
    """Tests for the dreams/reflection feature."""

    def test_reflection_schema_isolation(self, clean_env):
        """Verifies that insights generated by a reflection pass are correctly routed 
        to the reflection_insights backend collection with a trust_score of 0.85."""
        insights = "# Test Insight\n\nThis is a test reflection."
        meta = {"source_session_ids": ["test-1"], "log_count": 1}
        
        entry_id = save_reflection_insight(insights, meta)
        
        # Check the reflection_insights table was used
        from memtext.repositories.database import get_connection, get_db_path
        db_path = get_db_path()
        
        with get_connection(db_path) as conn:
            row = conn.execute(
                "SELECT * FROM reflection_insights WHERE id = ?", (entry_id,)
            ).fetchone()
            
            assert row is not None
            assert row["trust_score"] == 0.85
            assert row["source"] == "memtext-reflection-engine"
            assert "# Test Insight" in row["content"]

    def test_cli_reflect_execution(self, clean_env):
        """Mocks a series of 5 highly repetitive error logs, runs memtext reflect, 
        and validates that the CLI exits with code 0 and writes a summarized pattern entry."""
        # Add 5 repetitive error logs
        for i in range(5):
            add_log("Fixed bug: connection timeout error. Database issue on port 5432.", session=f"test-{i}")
        
        result = run_reflection_cycle(max_logs=5)
        
        assert result["status"] == "success"
        assert result["insights_count"] >= 1
        
        # Check that reflection insights were saved
        from memtext.repositories.database import get_connection, get_db_path
        db_path = get_db_path()
        
        with get_connection(db_path) as conn:
            row = conn.execute(
                "SELECT * FROM reflection_insights ORDER BY created_at DESC LIMIT 1"
            ).fetchone()
            
            assert row is not None
            assert "Recurring Patterns" in row["content"] or "Potential User Preferences" in row["content"]

    def test_token_budget_gating_trigger(self, clean_env):
        """Confirms that when raw logs exceed the defined token constraints, 
        the engine successfully triggers a compaction cycle."""
        # Add a log with enough content to exceed the default 4000 token threshold
        large_content = "Error: test " * 1500  # ~12000 characters = ~3000 tokens
        add_log(large_content)
        
        result = run_reflection_cycle(max_logs=1, max_tokens=100)
        
        # Should have triggered pruning
        assert result["pruning_status"] is not None
        assert "Pruned" in result["pruning_status"]

    def test_rule_based_reflection_extracts_patterns(self, clean_env):
        """Test rule-based reflection extracts error patterns and preferences."""
        from memtext.reflection import _rule_based_reflection
        
        log_payload = """
        Log (2024-01-01):
        - Fixed bug in authentication
        - Error: connection timeout
        - User prefers dark mode
        - Should use PostgreSQL over MySQL
        """
        
        result = _rule_based_reflection(log_payload)
        
        assert "# Reflection Insights" in result
        assert "error" in result.lower() or "bug" in result.lower() or "prefer" in result.lower()

    def test_estimate_tokens(self):
        """Test token estimation."""
        text = "Hello world " * 100  # 1100 characters
        tokens = estimate_tokens(text)
        assert tokens >= 270  # Allow some flexibility (~1100 // 4 = 275)

    def test_format_logs_for_reflection(self, clean_env):
        """Test log formatting for LLM analysis."""
        logs = [
            {"id": "1", "log_date": "2024-01-01", "content": "Log content 1"},
            {"id": "2", "log_date": "2024-01-02", "content": "Log content 2"},
        ]
        
        result = format_logs_for_reflection(logs)
        
        assert "Log (2024-01-01)" in result
        assert "Log (2024-01-02)" in result
        assert "---" in result

    def test_no_logs_returns_not_found(self, clean_env):
        """Test that no logs returns not_found status."""
        result = run_reflection_cycle(max_logs=5)
        
        assert result["status"] == "not_found"
        assert result["insights_count"] == 0


class TestReflectionCLI:
    """Integration tests for the reflect CLI command."""

    def test_no_logs_reflect(self, clean_env, monkeypatch):
        """Test reflect command with no logs."""
        from memtext.cli import main
        
        result = main(["reflect", "--limit", "5"])
        assert result == 0  # Should exit gracefully even with no logs

    def test_reflect_with_logs(self, clean_env):
        """Test reflect command creates insights from logs."""
        from memtext.cli import main
        
        add_log("Working on feature: authentication fix")
        add_log("Error: bug in database connection")
        
        result = main(["reflect", "--limit", "2"])
        assert result == 0