"""Memtext package - public API."""

from .core import (
    add_log,
    init_context,
    query_context,
    save_context,
    synthesize_memories,
)
from .db import (
    add_entry,
    add_reminder,
    add_shared_entry,
    add_webhook,
    complete_reminder,
    create_backup,
    create_template,
    delete_entry,
    get_all_reminders,
    get_db_path,
    get_db_version,
    get_entry,
    get_pending_reminders,
    get_shared_entries,
    get_template,
    init_db,
    list_backups,
    list_entries,
    list_templates,
    list_webhooks,
    make_shared,
    query_entries,
    remove_webhook,
    restore_backup,
    run_migrations,
    trigger_webhook,
    update_entry,
)

__all__ = [
    # Core
    "init_context",
    "save_context",
    "query_context",
    "add_log",
    "synthesize_memories",
    # DB
    "get_db_path",
    "get_db_version",
    "run_migrations",
    "init_db",
    "add_entry",
    "get_entry",
    "update_entry",
    "delete_entry",
    "list_entries",
    "query_entries",
    "add_shared_entry",
    "get_shared_entries",
    "make_shared",
    "create_template",
    "get_template",
    "list_templates",
    "create_backup",
    "list_backups",
    "restore_backup",
    "add_reminder",
    "get_pending_reminders",
    "get_all_reminders",
    "complete_reminder",
    "add_webhook",
    "list_webhooks",
    "remove_webhook",
    "trigger_webhook",
]
